name: Build and Release Docker Container

on:
  push:

jobs:
  build:
    runs-on: depot-ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run build (if needed)
        run: echo "No build step defined"

      - name: Run tests
        run: npm test

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .

      - name: Save Docker image to file
        run: |
          docker save ghcr.io/${{ github.repository }}:${{ github.ref_name }} -o image.tar

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: image.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
